### ISSUE TITLE
Compile Error with Unicode contained programs on Python

### ISSUE THREAD

**Issue by EAliakbar** [koala-team/ijust_server#3]
this problem can happens when some Unicode character (for example: Zero-width non-joiner character AKA nim-Fasele) accidentally places in code

**Comment by AminHP** [comment]
Does this problem occur in other languages?

You can check them using **compile.sh** scripts located in *project/modules/ijudge/scripts/programming_language*.

For example check your code in python3.5 using this simplified command:
`python3.5 -c "compile(open('mycode.py').read(), 'mycode.py', 'exec')"`

Thanks!

**Comment by salarnasiri** [comment]
fixed

**Comment by salarnasiri** [comment]
fixed
